# Generated by Django 2.2.4 on 2019-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(default=0, upload_to='', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
