# Generated by Django 2.2.4 on 2019-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pessoa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='url',
            field=models.CharField(default=0, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
