# Generated by Django 2.2.4 on 2019-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pessoa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='desc',
            field=models.TextField(default=0, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
