# Generated by Django 2.2.4 on 2019-08-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20190819_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pets.City', verbose_name='cidade'),
            preserve_default=False,
        ),
    ]
