# Generated by Django 2.2.4 on 2019-08-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20190819_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='distrito')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.City', verbose_name='cidade')),
            ],
        ),
    ]
