# Generated by Django 2.2.4 on 2019-08-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20190819_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pets.District', verbose_name='distrito'),
            preserve_default=False,
        ),
    ]
