# Generated by Django 2.2.4 on 2019-08-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_person_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.District', verbose_name='bairro'),
        ),
    ]
