# Generated by Django 2.2.4 on 2019-08-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20190819_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('desc', models.TextField(max_length=500, verbose_name='Descrição')),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('F', 'Femia')], max_length=255, verbose_name='Gênero')),
                ('cidade', models.CharField(max_length=2, verbose_name='Cidade')),
                ('especie', models.CharField(choices=[('G', 'Gato'), ('C', 'Cachorro')], max_length=255, verbose_name='Especie')),
                ('foto', models.FileField(upload_to='', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
