# Generated by Django 2.2.4 on 2019-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20190819_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
    ]
