# Generated by Django 2.2.4 on 2019-08-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_auto_20190819_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
    ]
