# Generated by Django 2.2.4 on 2019-08-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_auto_20190820_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='phone',
            new_name='telefone',
        ),
    ]
